version: 0.0.1

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9090
  adminConnectors:
  - type: http
    port: 9091

swagger:
  resourcePackage: com.saltside.bird.api
