/*
 * Bird-Registry
 * Bird registry
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.saltside.bird.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 * ErrorresponseSource
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-08-19T05:47:47.983Z")
public class ErrorSourcePointer {
	@JsonProperty("pointer")
	private String pointer = null;

	@JsonProperty("parameter")
	private String parameter = null;

	public ErrorSourcePointer pointer(String pointer) {
		this.pointer = pointer;
		return this;
	}

	/**
	 * Get pointer
	 * 
	 * @return pointer
	 **/
	@JsonProperty("pointer")
	@ApiModelProperty(value = "")
	public String getPointer() {
		return pointer;
	}

	public void setPointer(String pointer) {
		this.pointer = pointer;
	}

	public ErrorSourcePointer parameter(String parameter) {
		this.parameter = parameter;
		return this;
	}

	/**
	 * Get parameter
	 * 
	 * @return parameter
	 **/
	@JsonProperty("parameter")
	@ApiModelProperty(value = "")
	public String getParameter() {
		return parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ErrorSourcePointer errorresponseSource = (ErrorSourcePointer) o;
		return Objects.equals(this.pointer, errorresponseSource.pointer)
				&& Objects.equals(this.parameter, errorresponseSource.parameter);
	}

	@Override
	public int hashCode() {
		return Objects.hash(pointer, parameter);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ErrorresponseSource {\n");

		sb.append("    pointer: ").append(toIndentedString(pointer)).append("\n");
		sb.append("    parameter: ").append(toIndentedString(parameter)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
