/*
 * Bird-Registry
 * Bird registry
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.saltside.bird.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 * ErrorResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-08-19T05:47:47.983Z")
public class ErrorResponse {
	@JsonProperty("code")
	private String code = null;

	@JsonProperty("message")
	private String message = null;

	@JsonProperty("source")
	private ErrorSourcePointer source = null;

	public ErrorResponse code(String code) {
		this.code = code;
		return this;
	}

	/**
	 * custom error code
	 * 
	 * @return code
	 **/
	@JsonProperty("code")
	@ApiModelProperty(value = "custom error code")
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public ErrorResponse message(String message) {
		this.message = message;
		return this;
	}

	/**
	 * error message
	 * 
	 * @return message
	 **/
	@JsonProperty("message")
	@ApiModelProperty(value = "error message")
	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public ErrorResponse source(ErrorSourcePointer source) {
		this.source = source;
		return this;
	}

	/**
	 * Get source
	 * 
	 * @return source
	 **/
	@JsonProperty("source")
	@ApiModelProperty(value = "")
	public ErrorSourcePointer getSource() {
		return source;
	}

	public void setSource(ErrorSourcePointer source) {
		this.source = source;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ErrorResponse errorResponse = (ErrorResponse) o;
		return Objects.equals(this.code, errorResponse.code) && Objects.equals(this.message, errorResponse.message)
				&& Objects.equals(this.source, errorResponse.source);
	}

	@Override
	public int hashCode() {
		return Objects.hash(code, message, source);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class ErrorResponse {\n");

		sb.append("    code: ").append(toIndentedString(code)).append("\n");
		sb.append("    message: ").append(toIndentedString(message)).append("\n");
		sb.append("    source: ").append(toIndentedString(source)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
