/*
 * Bird-Registry
 * Bird registry
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.saltside.bird.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 * GETBirdsRequestLink
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-08-19T05:47:47.983Z")
public class ResponseLink {
	@JsonProperty("nextOffset")
	private String nextOffset = null;

	public ResponseLink nextOffset(String nextOffset) {
		this.nextOffset = nextOffset;
		return this;
	}

	/**
	 * Get nextOffset
	 * 
	 * @return nextOffset
	 **/
	@JsonProperty("nextOffset")
	@ApiModelProperty(value = "")
	public String getNextOffset() {
		return nextOffset;
	}

	public void setNextOffset(String nextOffset) {
		this.nextOffset = nextOffset;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		ResponseLink geTBirdsRequestLink = (ResponseLink) o;
		return Objects.equals(this.nextOffset, geTBirdsRequestLink.nextOffset);
	}

	@Override
	public int hashCode() {
		return Objects.hash(nextOffset);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class GETBirdsRequestLink {\n");

		sb.append("    nextOffset: ").append(toIndentedString(nextOffset)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
